server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: parking_system
    static_configs:
      - targets:
          - localhost
        labels:
          job: parking-api
          env: development
          __path__: /var/log/app/*.log # Ini baca file log lo